config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner
  belongs_to :breed
end

app/models/owner.rb
class Owner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:genre, :registered, :date_of_birth, :name, :owner_id, :last_time, :breed_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.haml
= form_for @dog, :html => { :class => "form-horizontal dog" } do |f|
  - if @dog.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@dog.errors.count, "error")
          prohibited this dog from being saved:
      .panel-body
        %ul
          - @dog.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :genre, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :genre, :class => 'form-control'
    = f.error_span(:genre)
  .form-group
    = f.label :registered, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :registered, :class => 'form-control'
    = f.error_span(:registered)
  .form-group
    = f.label :date_of_birth, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :date_of_birth, :class => 'form-control'
    = f.error_span(:date_of_birth)
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :owner_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :owner_id, :class => 'form-control'
    = f.error_span(:owner_id)
  .form-group
    = f.label :last_time, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_time, :class => 'form-control'
    = f.error_span(:last_time)
  .form-group
    = f.label :breed_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :breed_id, :class => 'form-control'
    = f.error_span(:breed_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        dogs_path, :class => 'btn btn-default'                       |

app/views/dogs/edit.html.haml
- model_class = Dog
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/dogs/index.html.haml
- model_class = Dog
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:genre)
      %th= model_class.human_attribute_name(:registered)
      %th= model_class.human_attribute_name(:date_of_birth)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:owner_id)
      %th= model_class.human_attribute_name(:last_time)
      %th= model_class.human_attribute_name(:breed_id)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @dogs.each do |dog|
      %tr
        %td= link_to dog.id, dog_path(dog)
        %td= dog.genre
        %td= dog.registered
        %td= dog.date_of_birth
        %td= dog.name
        %td= dog.owner_id
        %td= dog.last_time
        %td= dog.breed_id
        %td= l dog.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), |
            dog_path(dog), :class => 'btn btn-default btn-xs'        |
          = link_to t('.edit', :default => t("helpers.links.edit")), |
            edit_dog_path(dog), :class => 'btn btn-default btn-xs'   |
          = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
            dog_path(dog),                                                                                               |
            :method => :delete,                                                                                          |
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
            :class => 'btn btn-xs btn-danger'                                                                            |
= link_to t('.new', :default => t("helpers.links.new")), |
  new_dog_path,                                          |
  :class => 'btn btn-primary'                            |

app/views/dogs/new.html.haml
- model_class = Dog
.panel.panel-default 
  .panel-heading
    %h1= t '.text-center', :default => [:'helpers.titles.new', 'Novo %{model}'], :model => model_class.model_name.human.titleize
  .panel-body  
    = render :partial => 'form'

app/views/dogs/show.html.haml
- model_class = Dog
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:genre)
      \:
  %dd= @dog.genre
  %dt
    %strong
      = model_class.human_attribute_name(:registered)
      \:
  %dd= @dog.registered
  %dt
    %strong
      = model_class.human_attribute_name(:date_of_birth)
      \:
  %dd= @dog.date_of_birth
  %dt
    %strong
      = model_class.human_attribute_name(:name)
      \:
  %dd= @dog.name
  %dt
    %strong
      = model_class.human_attribute_name(:owner_id)
      \:
  %dd= @dog.owner_id
  %dt
    %strong
      = model_class.human_attribute_name(:last_time)
      \:
  %dd= @dog.last_time
  %dt
    %strong
      = model_class.human_attribute_name(:breed_id)
      \:
  %dd= @dog.breed_id
= link_to t('.back', :default => t("helpers.links.back")), |
  dogs_path, :class => 'btn btn-default'                   |
= link_to t('.edit', :default => t("helpers.links.edit")), |
  edit_dog_path(@dog), :class => 'btn btn-default'         |
= link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
  dog_path(@dog),                                                                                              |
  :method => 'delete',                                                                                         |
  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
  :class => 'btn btn-danger'                                                                                   |

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Petshop
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield